FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src

COPY PowerPlant/PowerPlant.GenerationService/*.csproj PowerPlant/PowerPlant.GenerationService/
COPY PowerPlant/PowerPlant.Domain/*.csproj PowerPlant/PowerPlant.Domain/
COPY Shared/Shared.Domain/*.csproj Shared/Shared.Domain/
COPY Shared/Shared.Infrastructure/*.csproj Shared/Shared.Infrastructure/

RUN dotnet restore PowerPlant/PowerPlant.GenerationService/PowerPlant.GenerationService.csproj

COPY . .
WORKDIR "/src/PowerPlant/PowerPlant.GenerationService"
RUN dotnet build "PowerPlant.GenerationService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PowerPlant.GenerationService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PowerPlant.GenerationService.dll"]
