FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src

COPY PowerPlant/PowerPlant.Services.Test/*.csproj PowerPlant/PowerPlant.Services.Test/
COPY PowerPlant/PowerPlant.Services/*.csproj PowerPlant/PowerPlant.Services/
COPY PowerPlant/PowerPlant.Domain/*.csproj PowerPlant/PowerPlant.Domain/
COPY PowerPlant/PowerPlant.Infrastructure/*.csproj PowerPlant/PowerPlant.Domain/

COPY Shared/Shared.Domain/*.csproj Shared/Shared.Domain/
COPY Shared/Shared.Infrastructure/*.csproj Shared/Shared.Domain/

RUN dotnet restore PowerPlant/PowerPlant.Services.Test/PowerPlant.Services.Test.csproj

COPY . .
WORKDIR "/src/PowerPlant/PowerPlant.Services.Test"
RUN dotnet build "PowerPlant.Services.Test.csproj" -c Release -o /app/build

FROM build AS testrunner
WORKDIR "/src/PowerPlant/PowerPlant.Services.Test"
CMD ["dotnet", "test", "--logger:trx"]

# run the unit tests
FROM build AS test
WORKDIR "/src/PowerPlant/PowerPlant.Services.Test"
RUN dotnet test --logger:trx

